- hosts: localhost
  connection: local
  vars_files:
    - ./vars.yml
  roles:
    #- { role: azure.azure_preview_modules }
    - ./modules

  tasks:
    # - name: Get VM information
    #   azure_rm_virtualmachine_facts:
    #     resource_group: "terraformvmrg"
    #     name: "ubuntu1604427"
    #   register: output
    # - debug:
    #     var: output

    # - name: Get facts for one managed disk
    #   azure_rm_managed_disk_facts:
    #     name: "{{ source_vm_name }}-osdisk"
    #     resource_group: "{{ resource_group }}"
    #   register: output
    # - debug:
    #     var: output

    - name: Create a snapshot by importing a managed disk from the same subscription.
      azure_rm_snapshot:
        resource_group: "{{ resource_group }}"
        name: "{{ snapshot_name }}"
        location: "{{ location }}"
        creation_data:
          create_option: Copy
          source_id: '/subscriptions/05be085b-86ea-4336-addc-38fd56051a9e/resourceGroups/mytfrg/providers/Microsoft.Compute/disks/PackerTemp-1574820192'
      register: output
    - debug:
        var: output
  
